# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown


defaults:
  title: Chu-Ming's thoughts
  description: A curious concoction of technology and philosophy.
author:  
  name: Chu-Ming
  # introduction: Chu-Ming
  email: changchuming@gmail.com
  github: changchuming
  facebook: changchuming
  site: changchuming.github.io
  bio: A technophile with too many interests. Currently a software engineer at Google. Loves turning every conversation into a philosophical one.
  email_md5: 6d35e4981839e54375182e5c2b2ca18f

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

url: https://changchuming.github.io #http://localhost:4000 