# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Chang Chu-Ming

description: A curious concoction of technology and philosophy.
introduction: Hello! I am Chu-Ming, an Electrical Engineering student at the National University of Singapore. I have a strong interest in Computer Science and I love discussing otherworldly concepts. You can find my blogs as well as my projects page on the sidebar. Ways to contact me can also be found here.
author:  
  name: Chang Chu-Ming
  email: changchuming@gmail.com
  github: changchuming
  facebook: changchuming
  site: changchuming.github.io
  bio: I am a technophile with too many interests. Here I blog about both technology-related stuff as well as philosophical thoughts.
  email_md5: 6d35e4981839e54375182e5c2b2ca18f

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://changchuming.github.io #http://localhost:4000 
